In [1]:
import pandas as pd

data = {
    "student_id": [1, 2, 3, 4, 5],
    "name": ["Akshaya", "Ravi", "Priya", "Kiran", "Neha"],
    "age": [20, 21, 19, 22, 20],
    "marks": [85, 78, 92, 60, 88],
    "city": ["Hyderabad", "Delhi", "Mumbai", "Chennai", "Hyderabad"],
    "passed": [True, True, True, False, True]
}

df = pd.DataFrame(data)
print(df)

   student_id     name  age  marks       city  passed
0           1  Akshaya   20     85  Hyderabad    True
1           2     Ravi   21     78      Delhi    True
2           3    Priya   19     92     Mumbai    True
3           4    Kiran   22     60    Chennai   False
4           5     Neha   20     88  Hyderabad    True

In [3]:
print(df[['age']])

   age
0   20
1   21
2   19
3   22
4   20

In [4]:
df[['age']]

   age
0   20
1   21
2   19
3   22
4   20

In [6]:
df.head()

   student_id     name  age  marks       city  passed
0           1  Akshaya   20     85  Hyderabad    True
1           2     Ravi   21     78      Delhi    True
2           3    Priya   19     92     Mumbai    True
3           4    Kiran   22     60    Chennai   False
4           5     Neha   20     88  Hyderabad    True

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  5 non-null      int64
 1   name        5 non-null      object
 2   age         5 non-null      int64
 3   marks       5 non-null      int64
 4   city        5 non-null      object
 5   passed      5 non-null      bool
dtypes: bool(1), int64(3), object(2)
memory usage: 337.0+ bytes

In [9]:
df.describe()

       student_id        age      marks
count    5.000000   5.000000   5.000000
mean     3.000000  20.400000  80.600000
std      1.581139   1.140175  12.601587
min      1.000000  19.000000  60.000000
25%      2.000000  20.000000  78.000000
50%      3.000000  20.000000  85.000000
75%      4.000000  21.000000  88.000000
max      5.000000  22.000000  92.000000

In [11]:
df[['name', 'marks']]

      name  marks
0  Akshaya     85
1     Ravi     78
2    Priya     92
3    Kiran     60
4     Neha     88

In [12]:
df[['marks']].sum()

marks    403
dtype: int64

In [15]:
df.loc[0]

student_id            1
name            Akshaya
age                  20
marks                85
city          Hyderabad
passed             True
Name: 0, dtype: object

In [27]:
df[['age']].loc[0:3]

   age
0   20
1   21
2   19
3   22

In [29]:
df[['age']].iloc[0:3]

   age
0   20
1   21
2   19

In [46]:
df[df['marks']>80]

   student_id     name  age  marks       city  passed grade
0           1  Akshaya   20     85  Hyderabad    True     B
2           3    Priya   19     92     Mumbai    True     A
4           5     Neha   20     88  Hyderabad    True     B

In [33]:
df[df['city']=='Hyderabad']

   student_id     name  age  marks       city  passed
0           1  Akshaya   20     85  Hyderabad    True
4           5     Neha   20     88  Hyderabad    True

In [37]:
df.sort_values(by = 'marks', ascending=False)

   student_id     name  age  marks       city  passed
2           3    Priya   19     92     Mumbai    True
4           5     Neha   20     88  Hyderabad    True
0           1  Akshaya   20     85  Hyderabad    True
1           2     Ravi   21     78      Delhi    True
3           4    Kiran   22     60    Chennai   False

In [38]:
df.sort_values(by = 'age', ascending=True)

   student_id     name  age  marks       city  passed
2           3    Priya   19     92     Mumbai    True
0           1  Akshaya   20     85  Hyderabad    True
4           5     Neha   20     88  Hyderabad    True
1           2     Ravi   21     78      Delhi    True
3           4    Kiran   22     60    Chennai   False

In [39]:
df.groupby('city')['marks'].mean()

city
Chennai      60.0
Delhi        78.0
Hyderabad    86.5
Mumbai       92.0
Name: marks, dtype: float64

In [47]:
df['grade'] = pd.cut(df['marks'], bins=[0,60,70,80,90,100], labels=['F','D','C','B','A' ])
df[['grade']]

  grade
0     B
1     C
2     A
3     F
4     B